DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS deck;
DROP TABLE IF EXISTS card;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role_id INTEGER NOT NULL,
  total_learned_time TEXT,
  created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted INTEGER DEFAULT 0,
  deleted_on TEXT,
  FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE role (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE groups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  public INTEGER DEFAULT 0,
  deleted INTEGER DEFAULT 0,
  FOREIGN KEY (owner_id) REFERENCES user (id)
);

CREATE TABLE deck (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  group_id INTEGER NOT NULL,
  public INTEGER DEFAULT 0,
  deleted INTEGER DEFAULT 0,
  FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE card (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  deck_id INTEGER NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  public INTEGER DEFAULT 0,
  deleted INTEGER DEFAULT 0,
  FOREIGN KEY (deck_id) REFERENCES deck (id)
);

